// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppApi.Models;

#nullable disable

namespace WebAppApi.Migrations
{
    [DbContext(typeof(ContextBD))]
    partial class ContextBDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppApi.Models.Administrador", b =>
                {
                    b.Property<int>("Id_admin_pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_admin_pk"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaN")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identif_cuenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("P_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_admin_pk");

                    b.HasIndex("Identif_cuenta")
                        .IsUnique()
                        .HasFilter("[Identif_cuenta] IS NOT NULL");

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("WebAppApi.Models.Direccion", b =>
                {
                    b.Property<int>("Id_direccion_pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_direccion_pk"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("Ubi_dire_ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubi_pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_direccion_pk");

                    b.HasIndex("PersonaId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("WebAppApi.Models.Empresa", b =>
                {
                    b.Property<int>("Id_empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_empresa"));

                    b.Property<string>("Ciudad_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_ref_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_Empres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_origen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interes_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NIT_empresa")
                        .HasColumnType("int");

                    b.Property<string>("Pais_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_empresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("WebAppApi.Models.Inmueble", b =>
                {
                    b.Property<int>("Id_inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_inmueble"));

                    b.Property<string>("Contacto_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_admin_pk")
                        .HasColumnType("int");

                    b.Property<string>("Identif_cuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_inmueble");

                    b.HasIndex("Id_admin_pk");

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("WebAppApi.Models.Persona", b =>
                {
                    b.Property<int>("Id_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_persona"));

                    b.Property<string>("Cc_id_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_ref_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Despc_interes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail_perfil_persona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaN")
                        .HasColumnType("datetime2");

                    b.Property<string>("P_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_persona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("WebAppApi.Models.ReporteEmpresa", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_ref_empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_queja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomb_ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres_apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tematica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_reporte");

                    b.ToTable("ReporteEmpresa");
                });

            modelBuilder.Entity("WebAppApi.Models.ReporteUsuario", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<string>("Celular_u")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cod_ref_usuario_u")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo_u")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion_queja_u")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomb_ciudad_u")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres_apellidos_u")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tematica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_reporte");

                    b.HasIndex("Cod_ref_usuario_u")
                        .IsUnique()
                        .HasFilter("[Cod_ref_usuario_u] IS NOT NULL");

                    b.ToTable("ReporteUsuario");
                });

            modelBuilder.Entity("WebAppApi.Models.Direccion", b =>
                {
                    b.HasOne("WebAppApi.Models.Persona", null)
                        .WithMany("Direccion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAppApi.Models.Inmueble", b =>
                {
                    b.HasOne("WebAppApi.Models.Administrador", "Administrador")
                        .WithMany("Inmuebles")
                        .HasForeignKey("Id_admin_pk");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("WebAppApi.Models.Administrador", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("WebAppApi.Models.Persona", b =>
                {
                    b.Navigation("Direccion");
                });
#pragma warning restore 612, 618
        }
    }
}
